-- GLO-72: promotional price flag on live Procedures and on DraftProcedures.
--
-- A promotional price is one the source conditions on something ("new clients
-- only", "limited time", "package of three") rather than quoting as the
-- standard rate. 17.4% of extracted priced rows are promotional and are
-- currently published as if they were standard rates.
--
-- THREE STATES, NOT TWO. The column is BIT NULL with NO DEFAULT, on purpose:
--
--   1    -- assessed, promotional
--   0    -- assessed, standard rate
--   NULL -- not assessed
--
-- Adding a DEFAULT 0 (or backfilling existing rows to 0) would assert "this is
-- a standard rate" about ~444 clinics' procedures that predate the extractor
-- and for which no promotional signal exists at all -- no source page, no
-- evidence quote, nothing to derive it from. On a price-comparison
-- marketplace that is a published false claim. A missing badge is merely
-- uninformative; a wrong badge is believed. So existing rows stay NULL.
--
-- Only ClinicIDs 623-629 are backfilled, by
-- scripts/backfillPromotionalFromIngestion.js, from locally held extraction
-- data with verified evidence quotes.
--
-- ADDITIVE AND REVERSIBLE. ALTER TABLE ... ADD of a nullable column with no
-- default is a metadata-only operation on SQL Server -- it does not rewrite
-- the table and does not touch existing rows, which matters on Azure SQL Basic
-- (5 DTU). To reverse, see the DROP block at the bottom of this file; dropping
-- the column loses the assessments but restores the prior schema exactly.
--
-- Until this migration runs, the API reads CAST(NULL AS BIT) and writes skip
-- the column (utils/procedureIsPromotionalColumn.js), so deploying the code
-- ahead of the migration is safe.

IF NOT EXISTS (
  SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'Procedures' AND COLUMN_NAME = 'IsPromotional'
)
BEGIN
  ALTER TABLE Procedures ADD IsPromotional BIT NULL;
  PRINT 'Added IsPromotional column to Procedures (all rows NULL = not assessed)';
END
ELSE
BEGIN
  PRINT 'IsPromotional column already exists in Procedures';
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'DraftProcedures' AND COLUMN_NAME = 'IsPromotional'
)
BEGIN
  ALTER TABLE DraftProcedures ADD IsPromotional BIT NULL;
  PRINT 'Added IsPromotional column to DraftProcedures (all rows NULL = not assessed)';
END
ELSE
BEGIN
  PRINT 'IsPromotional column already exists in DraftProcedures';
END
GO

-- ---------------------------------------------------------------------------
-- REVERSAL (do not run as part of the migration)
--
-- The column carries no constraints, no index and no default, so nothing else
-- has to be unwound first:
--
--   ALTER TABLE Procedures      DROP COLUMN IsPromotional;
--   ALTER TABLE DraftProcedures DROP COLUMN IsPromotional;
--
-- The API tolerates the column's absence (it falls back to CAST(NULL AS BIT)
-- within ~5 minutes of cache expiry), so the reversal does not require a code
-- rollback. It does discard the stored assessments; they can be regenerated by
-- re-running scripts/backfillPromotionalFromIngestion.js, which reads from the
-- ingestion database and not from prod.
-- ---------------------------------------------------------------------------
